"""admins profile_image_key

Revision ID: 2f23073050e3
Revises: a4e06ef32e5d
Create Date: 2026-06-12 09:31:05.220022

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f23073050e3'
down_revision: str | None = 'a4e06ef32e5d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('profile_image_key', sa.String(), nullable=True))
    op.drop_column('admins', 'profile_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('profile_image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('admins', 'profile_image_key')
    # ### end Alembic commands ###
